name: Deploy Docs
on:
  push:
    branches:
      - main  # 如果你的默认分支叫 master，请改为 master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          pip install mkdocs-material
          # 如果你还用了其他 mkdocs 插件，可以在这里加一行 pip install 插件名

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force